<div>
    <a href="http://isha.magento.com/shirts.html">
        <img style="width: 200px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM5z-cUSl9XQFlOViZn-znsJ-LLg61aVEyNL-3K43rUarA2GaFY6oGCleSaKCJQ_1k8DA&usqp=CAU" alt="img1">
    </a>

    <a href="http://isha.magento.com/hoodies.html">
        <img style="width: 200px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKNpCN4s6yuxf_ff8wscKEbIGBJEEyqRFEmkVKwNmrX_czmKSs_NXJxu4jdKUmXDiw_lc&usqp=CAU" alt="img2">
    </a>

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus voluptatibus numquam earum magnam saepe. Tempora alias perspiciatis ea sapiente labore!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita facilis neque sapiente soluta nam porro mollitia sint aliquid aperiam deleniti nesciunt nostrum sed, fugiat repellat similique debitis earum placeat dolor suscipit, quaerat, corrupti nobis commodi! Sit, asperiores iusto?</p>
</div>
